# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: paga-despues

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-2

# The `functions` block defines what code to deploy
functions:
  listUsers:
    handler: handler.listUsers
    events:
      - http:
          path: listUsers
          method: get
          cors: true
          integration: LAMBDA 
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: createUser
          method: post
          cors: true        
          integration: LAMBDA 
  listPaymentMethods:
    handler: handler.listPaymentMethods
    events:
      - http:
          path: listPaymentMethods
          method: get
          request:
            parameters:
              querystrings:
                url: true
          cors: true 
          integration: LAMBDA 
  createPayment:
    handler: handler.createPayment
    events:
      - http:
          path: createPayment
          method: post
          cors: true         
          integration: LAMBDA 
  createPaymentMethod:
    handler: handler.createPaymentMethod
    events:
      - http:
          path: createPaymentMethod
          method: post
          cors: true
          integration: LAMBDA 